[package]
name = "tpcli"
version = "0.0.1" # Dev
edition = "2024"
repository = "https://github.com/TeaserPaste/tpcli"

[package.metadata.dist]
# Phiên bản cargo-dist mà dự án này sử dụng
cargo-dist-version = "0.30.3"

# Các loại installer mà bạn muốn cung cấp cho người dùng
# shell: cho dân Linux/macOS (curl | sh)
# powershell: cho dân Windows (irm | iex)
installers = ["shell", "powershell"]

# Các mục tiêu (target) để build. 
# Ở đây mình chọn các loại phổ biến nhất hiện nay:
targets = [
    "x86_64-unknown-linux-gnu",   # Linux 64-bit
    "x86_64-apple-darwin",        # macOS Intel
    "aarch64-apple-darwin",       # macOS Apple Silicon (M1/M2/M3)
    "x86_64-pc-windows-msvc",     # Windows 64-bit
]

# Tự động tạo GitHub CI dựa trên cấu hình này
ci = ["github"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
inquire = "0.7.5"
edit = "0.1.5"
ureq = { version = "2.9", features = ["json"] }
keyring = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
directories = "5.0"
arboard = "3.3"
tempfile = "3.10"
regex = "1.10"
colored = "2.1"
url = "2.5"
comfy-table = "7.1"
chrono = "0.4"
base64 = "0.22"
atty = "0.2.14"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
