[package]
name = "tpc"
description = "CLI for TeaserPaste product"
version = "0.1.0" 
edition = "2024"
authors = ["TeaserPaste"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/TeaserPaste/tpcli"
keywords = ["cli", "tp", "teaserpaste", "cargo"]
exclude = ["target/*", "wix/*", "dist-workspace.toml"]

[package.metadata.wix]
upgrade-guid = "88923E65-EE1B-492A-8438-E3E39FF8F130"
path-guid = "0F2B1E55-2975-4F7E-A783-C71346668C68"
license = false
eula = false

[dependencies]
clap = { version = "4.4", features = ["derive"] }
inquire = "0.7.5"
edit = "0.1.5"
ureq = { version = "2.9", features = ["json"] }
keyring = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
directories = "5.0"
arboard = "3.3"
tempfile = "3.10"
regex = "1.10"
colored = "2.1"
url = "2.5"
comfy-table = "7.1"
chrono = "0.4"
base64 = "0.22"
atty = "0.2.14"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
